### ISSUE TITLE
ACMEv1 is being depreciated. 

### ISSUE THREAD

**Issue by robeadam** [f5devcentral/lets-encrypt-python#4]
Are there any plans to update this script to use ACMEv2?
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by f5-rahm** [comment]
I'll take a look @robeadam, but will likely be a little while. Quick research is that the original author of the shell script in this repo supports acmev2 in the dehydrated script, so it shouldn't take too much to rework with those changes as well as the changes to the name.com APIs since I made this.

**Comment by f5-rahm** [comment]
reconfigured, closing this out.
